package com.example.encryptapp.core.crypto

import com.example.encryptapp.core.domain.model.Algorithm
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import javax.crypto.BadPaddingException

/**
 * Unit tests for CryptoManager.
 *
 * Runs on JVM (not Android device) — CryptoManager uses only java.* and javax.*
 * packages which are part of the standard JDK.
 */
class CryptoManagerTest {

    private lateinit var crypto: CryptoManager

    @BeforeEach
    fun setUp() {
        crypto = CryptoManager()
        crypto.iterations = 10000
    }

    // ── Cross-Platform Compatibility ─────────────────────────────────

    /**
     * Verify Kotlin CryptoManager can decrypt ciphertext produced by Python crypto_manager.py.
     * These test vectors were generated by the Python reference implementation.
     */
    @Test
    fun `decrypt Python-generated AES-256 ciphertext`() {
        val encrypted = "DCX02TStOlh9mN7rfzzgAoKttXiCm6hsIGf+FbVhz8f3kGhvclYlxOqhuWUfmAow"
        val result = crypto.decryptText(encrypted, "test", Algorithm.AES_256)
        assertEquals("hello", result)
    }

    @Test
    fun `decrypt Python-generated AES-128 ciphertext`() {
        val encrypted = "r+qNlJi5iWsX7LfLKWsjcNrDlmDW6bfK2ARAPX3rOFBUq8i7CdzJS5NqUt8xNOi1"
        val result = crypto.decryptText(encrypted, "mypassword", Algorithm.AES_128)
        assertEquals("hello world", result)
    }

    @Test
    fun `decrypt Python-generated AES-192 ciphertext`() {
        val encrypted = "452+rxgUE/COpdnsmJzN+ZTcwW38RWOD/Ovetz1441Rejzew0cYWs2Oj5cuv9mwM"
        val result = crypto.decryptText(encrypted, "pass456", Algorithm.AES_192)
        assertEquals("test123", result)
    }

    // ── Text Round-Trip ──────────────────────────────────────────────

    @Test
    fun `encrypt and decrypt text round-trip AES-256`() {
        val encrypted = crypto.encryptText("Hello World!", "mySecret", Algorithm.AES_256)
        assertNotNull(encrypted)
        assertTrue(encrypted.isNotEmpty())
        val decrypted = crypto.decryptText(encrypted, "mySecret", Algorithm.AES_256)
        assertEquals("Hello World!", decrypted)
    }

    @Test
    fun `encrypt and decrypt text round-trip AES-128`() {
        val encrypted = crypto.encryptText("Test data 123", "pass", Algorithm.AES_128)
        val decrypted = crypto.decryptText(encrypted, "pass", Algorithm.AES_128)
        assertEquals("Test data 123", decrypted)
    }

    @Test
    fun `encrypt and decrypt text round-trip AES-192`() {
        val encrypted = crypto.encryptText("Another test!", "key192", Algorithm.AES_192)
        val decrypted = crypto.decryptText(encrypted, "key192", Algorithm.AES_192)
        assertEquals("Another test!", decrypted)
    }

    @Test
    fun `encrypt and decrypt unicode text`() {
        val text = "你好世界 🌍 — Café naïveté"
        val encrypted = crypto.encryptText(text, "unicodePwd", Algorithm.AES_256)
        val decrypted = crypto.decryptText(encrypted, "unicodePwd", Algorithm.AES_256)
        assertEquals(text, decrypted)
    }

    @Test
    fun `encrypt long text`() {
        val text = "A".repeat(10000)
        val encrypted = crypto.encryptText(text, "longPass", Algorithm.AES_256)
        val decrypted = crypto.decryptText(encrypted, "longPass", Algorithm.AES_256)
        assertEquals(text, decrypted)
    }

    // ── Edge Cases ───────────────────────────────────────────────────

    @Test
    fun `encrypt empty string returns empty`() {
        val result = crypto.encryptText("", "password", Algorithm.AES_256)
        assertEquals("", result)
    }

    @Test
    fun `decrypt empty string returns empty`() {
        val result = crypto.decryptText("", "password", Algorithm.AES_256)
        assertEquals("", result)
    }

    @Test
    fun `different passwords produce different ciphertext`() {
        val text = "Same text"
        val enc1 = crypto.encryptText(text, "password1", Algorithm.AES_256)
        val enc2 = crypto.encryptText(text, "password2", Algorithm.AES_256)
        // Due to random salt/IV, they're always different, but also different keys
        assertNotEquals(enc1, enc2)
    }

    @Test
    fun `same password and text produces different ciphertext due to random salt`() {
        val text = "Test"
        val enc1 = crypto.encryptText(text, "pwd", Algorithm.AES_256)
        val enc2 = crypto.encryptText(text, "pwd", Algorithm.AES_256)
        // Random salt + IV means each encryption is unique
        assertNotEquals(enc1, enc2)
        // But both decrypt to the same text
        assertEquals(text, crypto.decryptText(enc1, "pwd", Algorithm.AES_256))
        assertEquals(text, crypto.decryptText(enc2, "pwd", Algorithm.AES_256))
    }

    // ── Error Handling ───────────────────────────────────────────────

    @Test
    fun `wrong password throws on decrypt`() {
        val encrypted = crypto.encryptText("secret data", "correctPwd", Algorithm.AES_256)
        assertThrows<Exception> {
            crypto.decryptText(encrypted, "wrongPwd", Algorithm.AES_256)
        }
    }

    @Test
    fun `wrong algorithm throws on decrypt`() {
        val encrypted = crypto.encryptText("data", "pwd", Algorithm.AES_256)
        assertThrows<Exception> {
            crypto.decryptText(encrypted, "pwd", Algorithm.AES_128)
        }
    }

    @Test
    fun `invalid base64 throws`() {
        assertThrows<IllegalArgumentException> {
            crypto.decryptText("not-valid-base64!!!", "pwd", Algorithm.AES_256)
        }
    }

    @Test
    fun `too short data throws`() {
        // Need valid base64 of at least SALT_SIZE + IV_SIZE bytes
        val tooShort = java.util.Base64.getEncoder().encodeToString(ByteArray(10))
        assertThrows<IllegalArgumentException> {
            crypto.decryptText(tooShort, "pwd", Algorithm.AES_256)
        }
    }

    @Test
    fun `tampered ciphertext fails`() {
        val encrypted = crypto.encryptText("data", "pwd", Algorithm.AES_256)
        // Tamper with a middle byte
        val bytes = java.util.Base64.getDecoder().decode(encrypted)
        bytes[bytes.size / 2] = (bytes[bytes.size / 2] xor 0xFF).toByte()
        val tampered = java.util.Base64.getEncoder().encodeToString(bytes)
        assertThrows<Exception> {
            crypto.decryptText(tampered, "pwd", Algorithm.AES_256)
        }
    }

    // ── Iterations ───────────────────────────────────────────────────

    @Test
    fun `different iterations produce different keys`() {
        crypto.iterations = 1000
        val enc1 = crypto.encryptText("text", "pwd", Algorithm.AES_256)

        crypto.iterations = 5000
        val enc2 = crypto.encryptText("text", "pwd", Algorithm.AES_256)

        // Decrypt each with the correct iteration count
        assertEquals("text", crypto.decryptText(enc1, "pwd", Algorithm.AES_256))

        // enc2 with iterations=5000 won't decrypt correctly with iterations still at 5000
        assertEquals("text", crypto.decryptText(enc2, "pwd", Algorithm.AES_256))

        // But enc1 (iterations=1000) should fail with current iterations=5000
        crypto.iterations = 5000
        assertThrows<Exception> {
            crypto.decryptText(enc1, "pwd", Algorithm.AES_256)
        }
    }

    // ── File Encryption Round-Trip ───────────────────────────────────

    @Test
    fun `encrypt and decrypt file round-trip`() {
        val originalData = "This is test file content.\nWith multiple lines.\nAnd some bytes:  ÿ\n".repeat(100)
        val originalBytes = originalData.toByteArray(Charsets.UTF_8)

        // Encrypt
        val inputStream = ByteArrayInputStream(originalBytes)
        val encryptedOutput = ByteArrayOutputStream()
        crypto.encryptFile(
            inputStream, encryptedOutput,
            fileSize = originalBytes.size.toLong(),
            password = "filePass",
            algorithm = Algorithm.AES_256
        )

        val encryptedBytes = encryptedOutput.toByteArray()
        assertTrue(encryptedBytes.size > originalBytes.size) // Should be larger due to salt + iv + padding

        // Decrypt
        val encryptedInput = ByteArrayInputStream(encryptedBytes)
        val decryptedOutput = ByteArrayOutputStream()
        crypto.decryptFile(
            encryptedInput, decryptedOutput,
            fileSize = encryptedBytes.size.toLong(),
            password = "filePass",
            algorithm = Algorithm.AES_256
        )

        val decryptedBytes = decryptedOutput.toByteArray()
        assertArrayEquals(originalBytes, decryptedBytes)
    }

    @Test
    fun `encrypt and decrypt small file`() {
        val originalBytes = "Hi".toByteArray(Charsets.UTF_8)

        val inputStream = ByteArrayInputStream(originalBytes)
        val encryptedOutput = ByteArrayOutputStream()
        crypto.encryptFile(inputStream, encryptedOutput, originalBytes.size.toLong(), "pwd", Algorithm.AES_256)

        val encryptedInput = ByteArrayInputStream(encryptedOutput.toByteArray())
        val decryptedOutput = ByteArrayOutputStream()
        crypto.decryptFile(encryptedInput, decryptedOutput,
            encryptedOutput.toByteArray().size.toLong(), "pwd", Algorithm.AES_256)

        assertArrayEquals(originalBytes, decryptedOutput.toByteArray())
    }

    @Test
    fun `encrypt and decrypt large file with progress`() {
        val originalBytes = ByteArray(1024 * 1024) // 1MB
        java.security.SecureRandom().nextBytes(originalBytes)

        val progressUpdates = mutableListOf<Pair<Long, Long>>()

        val inputStream = ByteArrayInputStream(originalBytes)
        val encryptedOutput = ByteArrayOutputStream()
        crypto.encryptFile(
            inputStream, encryptedOutput,
            fileSize = originalBytes.size.toLong(),
            password = "pwd",
            algorithm = Algorithm.AES_256,
            onProgress = { processed, total -> progressUpdates.add(processed to total) }
        )

        assertTrue(progressUpdates.isNotEmpty())
        assertTrue(progressUpdates.last().first >= originalBytes.size)

        // Decrypt
        val encryptedBytes = encryptedOutput.toByteArray()
        val encryptedInput = ByteArrayInputStream(encryptedBytes)
        val decryptedOutput = ByteArrayOutputStream()
        crypto.decryptFile(
            encryptedInput, decryptedOutput,
            fileSize = encryptedBytes.size.toLong(),
            password = "pwd",
            algorithm = Algorithm.AES_256
        )

        assertArrayEquals(originalBytes, decryptedOutput.toByteArray())
    }

    @Test
    fun `decrypt file too small throws`() {
        val tooSmall = ByteArray(10)
        val inputStream = ByteArrayInputStream(tooSmall)
        val outputStream = ByteArrayOutputStream()

        assertThrows<IllegalArgumentException> {
            crypto.decryptFile(inputStream, outputStream, tooSmall.size.toLong(), "pwd", Algorithm.AES_256)
        }
    }

    @Test
    fun `decrypt file with wrong password throws`() {
        val originalBytes = "test data".toByteArray()

        val inputStream = ByteArrayInputStream(originalBytes)
        val encryptedOutput = ByteArrayOutputStream()
        crypto.encryptFile(inputStream, encryptedOutput, originalBytes.size.toLong(), "correctPwd", Algorithm.AES_256)

        val encryptedBytes = encryptedOutput.toByteArray()
        val encryptedInput = ByteArrayInputStream(encryptedBytes)
        val decryptedOutput = ByteArrayOutputStream()

        assertThrows<Exception> {
            crypto.decryptFile(encryptedInput, decryptedOutput, encryptedBytes.size.toLong(), "wrongPwd", Algorithm.AES_256)
        }
    }

    // ── Algorithm Key Lengths ────────────────────────────────────────

    @Test
    fun `algorithm key lengths are correct`() {
        assertEquals(16, Algorithm.AES_128.keyLengthBytes)
        assertEquals(24, Algorithm.AES_192.keyLengthBytes)
        assertEquals(32, Algorithm.AES_256.keyLengthBytes)
    }

    @Test
    fun `Algorithm fromDisplayName returns correct enum`() {
        assertEquals(Algorithm.AES_128, Algorithm.fromDisplayName("AES-128"))
        assertEquals(Algorithm.AES_192, Algorithm.fromDisplayName("AES-192"))
        assertEquals(Algorithm.AES_256, Algorithm.fromDisplayName("AES-256"))
        assertEquals(Algorithm.AES_256, Algorithm.fromDisplayName("unknown"))
    }
}
